#!/bin/sh /etc/rc.common

START=90

start() {
    freemem=`awk '/MemFree/ { printf "%.3f \n", $2/1024 }' /proc/meminfo | awk '{print int($freemem)}'`
    let freemem=freemem-30
    /usr/bin/memtester $freemem 2 > /tmp/mem.log
    /usr/bin/aging_test 4 131072 32 200
}
